language: go
sudo: false
go:
  - 1.4
  - tip
env:
  - GOARCH=amd64
addons:
  apt:
    packages:
      - rsyslog
before_install:
  - sed -i "s|git://github.com/tsuru/gandalf.git|https://github.com/tsuru/gandalf|g" .git/config
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - make get GO_EXTRAFLAGS=-x
before_script:
  - rsyslogd &
script:
  - make test GO_EXTRAFLAGS=-x
  - rm -rf Godeps
  - ./check-fmt.sh
services: mongodb
