language: go
go:
  - 1.1.1
  - 1.2.2
  - tip
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install mercurial bzr -qq
install:
  - make get
script:
  - make test
services: mongodb
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
