language: go
go:
  - 1.2.2
  - 1.3
  - tip
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install mercurial bzr -qq
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - make get
script:
  - make test
services: mongodb
