language: go
sudo: required
go:
  - 1.6.3
  - 1.7
  - tip
env:
  global:
    - GOARCH=amd64
addons:
  apt:
    packages:
      - rsyslog
before_script:
  - rsyslogd &
script:
  - make test
  - ./check-fmt.sh
  - go build -ldflags "-linkmode external -extldflags -static" webserver/main.go
services: mongodb
matrix:
  allow_failures:
    - go: tip
after_success:
  - bash <(curl -s https://codecov.io/bash)
