language: go
sudo: required
go:
  - 1.5.3
  - 1.6
  - tip
env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1
addons:
  apt:
    packages:
      - rsyslog
before_script:
  - rsyslogd &
script:
  - make test
  - ./check-fmt.sh
  - go build -ldflags "-linkmode external -extldflags -static"
services: mongodb
matrix:
  allow_failures:
    - go: tip
