language: go
go:
  - 1.2.2
  - 1.3
  - tip
env:
  - GOARCH=amd64
before_install:
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - make get
script:
  - make test
  - ./check-fmt.sh
services: mongodb
