language: go
go:
  - 1.4
  - tip
env:
  - GOARCH=amd64
before_install:
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - make get GO_EXTRAFLAGS=-x
before_script:
  - if [ "$TRAVIS_REPO_SLUG" != "tsuru/gandalf" ]; then cd ..; mv gandalf ../tsuru; cd ../tsuru/gandalf; fi
script:
  - make test GO_EXTRAFLAGS=-x
  - ./check-fmt.sh
services: mongodb
